### PR TITLE
Stripe feature

### PR DESCRIPTION
**Pull request by Jerrika**
updated the components on the client side to create the cart checkout [cart, cartItem, categoryMenu, deleteBtn, productItem, and productList] in the client utils I updated the GlobalState, actions, helpers, and added a checkout to Queries. Added Models Category, Order, and Product. I also updated Schema files.

### CODE REVIEW

**Comment by harrismhurley** [comment]
saw you copied and pasted from the activity, this activity deals w products not events. you gotta tweak the files to work w this project

**Comment by Jerrika** [comment]
I understand that.  I saw the user and events in the code and will update.
I also wasn't too sure about the front functionality I cant get my code to
build I’m having a similar issur Kristin had and i figuted it would be
easier to update than to leave out anything we may need. I can update it,
just wanted to make sure I was headed in the right direction.


My questions are:

Update products to events? (Which u confirmed) kinda.

Remove the category components and code that goes along with it?

If I’m tweaking the code which parts specifically need to be tweaks.

Just Event/Products, Cart, Cart Items. I’m not a 100% either but I’m making
an attempt.


Any help would be appreciated.

**Comment by harrismhurley** [comment]
totally i gotchu, and im definitely thankful for you grinding on a sunday to get this proj done. in the main branch, in the components folder, there is a home folder. in the home folder there is a component called activeEvent. activeEvent is the bottom right component on the screen when you render it. the activeEvent has a button right now it says take action. all we have to do is tie a chakraUI model to that button where users can input card info and pay. no need for carts or list we are only purchasing one event at a time. check out this link for more info on the model we are using (https://v2.chakra-ui.com/docs/components/modal). if i can provide any more info please let me know

**Comment by harrismhurley** [comment]
Q: Update products to events? (Which u confirmed) kinda.
A: Yes in the appropriate scripts change "products" to "events". make sure you follow the structure of the event model and add some comments because the model will change by tuesday.

Q: Remove the category components and code that goes along with it?
A: Yes remove all the components. there should only be one new component for the payment model. this component should go in the client/src/components/home/addEvent directory. 

Key points:
* Only one new component in the home folder (if possible)
* Return the original Queries, with these deletions we cannot use apollo to test. 
* Go through most of the .js files you changed and return them to the original, we should be good just attaching payment to the events we have

**Comment by Jerrika** [comment]
Thank you for taking the time out to help me. Ill get started on this shortly. Sent from my iPhoneOn Aug 11, 2024, at 3:47 PM, harrismhurley ***@***.***> wrote:﻿
Q: Update products to events? (Which u confirmed) kinda.
A: Yes in the appropriate scripts change "products" to "events". make sure you follow the structure of the event model and add some comments because the model will change by tuesday.
Q: Remove the category components and code that goes along with it?
A: Yes remove all the components. there should only be one new component for the payment model. this component should go in the client/src/components/home/addEvent directory.
Key points:

Only one new component in the home folder (if possible)
Return the original Queries, with these deletions we cannot use apollo to test.
Go through most of the .js files you changed and return them to the original, we should be good just attaching payment to the events we have

**Pull request closed without merging**
